<?php

/**
 * @file
 * Placeholder module file for Islandora Sample Content Generator.
 */

/**
 * Implements hook_theme().
 */
function islandora_scg_theme() {
  return array(
    'islandora_scg_metadata_ds' => array(
      'variables' => array(
        'metadata' => NULL,
      ),
      'template' => 'theme/islandora_scg_metadata_ds',
    ),
  );
}

/**
 * Implements hook_preprocess_theme().
 */
function islandora_scg_preprocess_islandora_scg_metadata_ds(array &$variables) {
  // Read the sample metadata file.
  $sample_metadata = &drupal_static(__FUNCTION__);
  if (!isset($sample_metadata)) {
    $path = $variables['metadata_file'];
    $sample_metadata = file($path);
  }
  // Grab a random row from the sample metadata file.
  $random_line_number = array_rand($sample_metadata);
  $metadata = explode("\t", $sample_metadata[$random_line_number]);

  // Populate the singleton and repeatable variables.
  $variables['title'] = htmlspecialchars($metadata[0]);
  $variables['date_issued'] = htmlspecialchars($metadata[1]);

  $place_names = explode(';', $metadata[2]);
  $variables['geographics'] = array();
  foreach ($place_names as &$place_name) {
    $place_name = trim($place_name);
    $place_name = htmlspecialchars($place_name);
    $variables['geographics'][] = $place_name;
  }

  $topics = explode(';', $metadata[3]);
  $variables['topics'] = array();
  foreach ($topics as &$topic) {
    $topic = trim($topic);
    $topic = htmlspecialchars($topic);
    $variables['topics'][] = $topic;
  }

  $variables['abstract'] = htmlspecialchars(trim($metadata[4]));
  unset($variables['metadata_file']);
}
