<?php

/**
 * @file
 * An implementation of a Newspaper issue content type sample content generator.
 */

/**
 * A class that generates sample newspaper content.
 */
class IslandoraSampleNewspaperIssueGenerator extends IslandoraSampleContentGenerator {
  public function generateContent() {
    // input folder
    //   issue 1
    //     MODS.xml
    //     1
    //       OBJ.tif
    //     2
    //       OBJ.tif
    //   issue 2
    //     MODS.xml
    //     1
    //       OBJ.tif
    //     2
    //       OBJ.tif
  }

  public function loadContent() {
    //
  }


}
