<?php

/**
 * @file
 * An implementation of a Book content type sample content generator.
 */

/**
 * A class that generates sample book content.
 */
class IslandoraSampleBookGenerator extends IslandoraSampleContentGenerator {
  public function generateContent() {
    // input folder
    //   book 1
    //     MODS.xml
    //     1
    //       OBJ.tif
    //     2
    //       OBJ.tif
    //   book 2
    //     MODS.xml
    //     1
    //       OBJ.tif
    //     2
    //       OBJ.tif
  }

  public function loadContent() {
    //
  }


}
