Whytecliff, B.C.	1925	Some people on a dock in Whytecliff, B.C.
Boating at Rainbow Lodge, Alta Lake, B.C.	1952	Two people shown on a dock at Alta Lake, B.C.
Municipal Hall of Maple Ridge, Haney, B.C.	1963	Maple Ridge municipal hall in Haney, B.C.
Cloverdale, B.C.	1954	A street in Cloverdale, B.C. A hotel, some storefronts and some automobiles are shown.
Lougheed Highway, Haney, B.C.	1964	Lougheed Highway in Haney, B.C. Some automobiles and storefronts are shown.
Court House and Government Agency, New Westminster, B.C.	1909	A court house and government agency in New Westminster, B.C.
Post Office, New Westminster	1911	Post office building in New Westminster, B.C. Some pedestrians are shown.
Exhibition Buildings - New Westminster B.C.	1907	Exhibition buildings at Queen's Park, New Westminster, B.C.
R.A. and I. Exhibition Grounds, Queen's Park, New Westminster, B.C.	1905	Exhibition grounds at Queen's Park, New Westminster, B.C. A crowd of people is shown.
Steel Bridge across Fraser River, New Westminster, B.C.	1905	A close up look at the steel bridge across the Fraser River at New Westminster, B.C.
City Market, New Westminster, B.C.	1916	City market at the waterfront in New Westminster, B.C.
Harrison Hot Springs Hotel, Harrison Lake, B.C.	1942	The Harrison Hot Springs Hotel at Harrison Lake, B.C. Some people are shown walking on the walkway outside the hotel.
Snug Cove Landing, Bowen Island, B.C.	1953	A boat in Snug Cove, Bowen Island, B.C. Three people are shown watching the boat.
Hotel Bungalows, Bowen Island	1941	Hotel bungalows and grounds on Bowen Island, B.C. Some people are shown sitting on benches outside of the bungalows.
Mt Strahan Lodge, The Guest House, Bowen Island	1931	The guest house at Mt Strahan Lodge at Bowen Island, B.C.
Horse Shoe Bay, Bowen Island	1916	Some boats in Horseshoe Bay, Bowen Island, B.C.
Sailing and Swimming at Cultus Lake BC.	1949	Some people sailing and swimming at Cultus Lake, B.C.
Swans Point Picnic Grounds at Hatzic Lake near Mission.	1958	Numerous people on the shore and pier at Hatzic Lake, B.C.
Some Vancouver B.C. Schools	1912	Five different Vancouver, B.C. schools.
Marine Drive, North Shore, Vancouver BC	1917	Marine Drive on the North Shore, Vancouver, B.C. An automobile is shown on the road.
Potatoes Grow Big Here at Horseshoe Bay, B.C.	1944	A horse drawn wagon with giant potatoes on it. A man is shown on top of the giant potatoes.
Lihumitson Canyon, Chilliwack B.C.	1926	Several people observing a waterfall at Lihumitson Canyon in Chilliwack, B.C.
Ruskin Power Plant, near Mission City, B.C.	1952	The Ruskin Power Plant near Mission City, B.C. A bridge is shown leading to the power plant.
Second Narrows Bridge, Vancouver, B.C.	1927	The Second Narrows Bridge in Vancouver, B.C. Mountains in the distance are shown.
Creston, B.C. - Looking West	1952	An aerial view of Creston, B.C. looking west. Surrounding mountains are shown.
Village of Creston, B.C.	1952	An aerial view of the village of Creston, B.C. Surrounding mountains are shown.
General Hospital, Chilliwack, BC	1947	A general hospital in Chilliwack, B.C.
Vedder River, Near Chilliwack, B.C.	1924	The Vedder River near Chilliwack, B.C.
Floodwaters - Chiliwack, B.C.	1951	The Chilliwack Central School shown surrounded by floodwaters.
Soldiers Memorial Chilliwack B.C.	1942	A soldiers memorial in Chilliwack, B.C.
Glacier House Hotel, Glacier, B.C.	1915	Glacier House Hotel in Glacier, B.C. Some smoke is shown coming out of the building's chimney.
Swiss Guide and party on the Great Glacier, B.C.	1947	A mountain guide and party on the Great Glacier in B.C.
C.R.L. Co's Mill Capacity 200,000 Ft a Day, Golden, B.C.	1910	The C.R.L. Co. mill in Golden, B.C. The Selkirk mountains are shown in the background.
Bird's eye, Golden B.C.	1911	A bird's eye view of Golden, B.C.
Bridge At Cultus Lake, Chilliwack, B.C.	1950	A small bridge over part of Cultus Lake, B.C.
Method of spraying Hops at Chilliwack, Hop gardens	1912	Several men spraying hops at a hop garden in Chilliwack, B.C.
Baker Street Cranbrook, B.C.	1909	Baker Street in Cranbrook, B.C. Some storefronts and pedestrians are shown.
Pack Bridge Elk River	1907	A pack bridge over the Elk River near Fernie, B.C.
Lumbering, Vancouver, B.C.	1907	Four horses pulling a section of a log in Vancouver, B.C. Three men are shown on and around the log.
B.C. Spruce Mills Ltd., Lumberton, B.C.	1928	Two horses pulling a large log in Lumberton, B.C. Two men are shown by the horses.
Taking it Easy Near Vancouver, B.C.	1910	Four men and a dog on and around a tree that is being felled near Vancouver, B.C.
British Columbia Firs	1906	A man standing among some large British Columbia Fir trees.
A B.C. Walking Stick, Vancouver B.C.	1912	Two men cutting down a large tree in Vancouver, B.C.
Lumbering Scenes in British Columbia: Ox Teams	1905	A team of oxen pulling logs in British Columbia. Several men are shown around the oxen.
St-Eugene's Hospital - Cranbrook, B.C.	1953	St. Eugene Hospital in Cranbrook, B.C. An automobile is shown parked in front of the hospital.
Garden at C.P.R. Station, Cranbrook, B.C.	1946	A man standing in the garden at the Candian Pacific Railway station in Cranbrook, B.C.
CNPC Co. Office Fernie	1940	The Crows Nest Pass Coal Company's office in Fernie, B.C. An automobile is shown parked in front of the building.
Fernie, B.C. after the great fire, Aug. 1st 1908	1909	Fernie, B.C. after the great fire. Some buidings and rubble are shown.
Coke Ovens and Mount Fernie, Fernie, B.C.	1913	Coke ovens in Fernie, B.C. Some buildings and Mount Fernie are shown behind the coke ovens.
Victoria Avenue, Fernie, B.C.	1904	Victoria Avenue in Fernie, B.C. after the great fire. A horse drawn wagon and some storefronts are shown.
Toby Canyon Invermere BC	1929	A bridge crossing Toby Canyon in Invermere, B.C. An automobile is shown on the bridge.
Alberni, V.I., B.C.	1947	Partial view of Alberni, B.C. Some utility poles and buildings are shown.
B. S. & W. Pulp Mill Port Alberni, B.C.	1949	The B.S. & W. Pulp Mill in Port Alberni, B.C.
Argyle Street Port Alberni, B.C.	1949	Argyle Street in Port Alberni, B.C. Some storefronts and electric lines are shown.
Totem Pole Alert Bay-B.C.	1954	A totem pole in Alert Bay, B.C.
BC Packers' Store, Alert Bay, BC.	1939	The B.C. Packers' Store in Alert Bay, B.C. A totem pole is shown out front of the store.
Baptist Church Cranbrook, B.C.	1906	A baptist church in Cranbrook, B.C.
Westminster Ave. Chilliwack, B.C.	1933	Westminster Avenue in Chilliwack, B.C. Some automobiles and storefronts are shown.
Logging in British Columbia, Felling a Giant Tree	English	Two men felling a large tree in British Columbia.
Goodacre Lake, Victoria, B.C.	1909	Two women shown walking on a walkway beside Goodacre Lake in Victoria, B.C.
Camping Near Victoria, B.C.	1908	Three people shown sitting on the shore overlooking the water near Victoria, B.C.
Kitsilano Beach, Vancouver	1911	Numerous people shown on the beach and in the water at Kitsilano Beach, Vancouver, B.C. A boat is shown in the water.
Hastings St., East, Vancouver	1909	Hastings Street east in Vancouver, B.C. Some pedestrians, storefronts and a street railroad are shown.
No. 2. Tunnel, Field, B.C.	1910	Two tunnel entrances at Field, B.C.
English Bay, Vancouver, B.C.	1908	Two women sitting on a bench looking out at English Bay, Vancouver, B.C.
Granville St., South, Vancouver	1908	Granville Street south in Vancouver, B.C. Some storefronts, pedestrians and a street railroad are shown.
Macking Port, Victoria, B.C.	1911	A ship at Macking Port in Victoria, B.C. Some people are shown on the wharf at the port.
First Canyon Capilano, B.C.	1953	First Canyon at Capilano, B.C.
Tipperary Tea Gardens at the Summit of Capilano Canyon Vancouver, B.C.	1920	The Tipperary Tea Gardens at the summit of Capilano Canyon, Vancouver, B.C.
Princess Victoria Entering Harbour, Victoria, B.C.	1915	The Princess Victoria ship entering the Victoria, B.C. harbour.
Beacon Hill Park, Victoria, B.C.	1907	A walkway and a strange shaped tree in Beacon Hill Park, B.C.
Gold Stream, Nr Victoria, B.C.	1909	Two women standing beside the Goldstream River near Victoria, B.C. A man is shown sitting on a large rock by the stream.
Snow mushrooms, Lardo, B.C.	1906	Two tree stumps covered with snow in Lardeau, B.C. A few small stumps covered with snow are shown in the background.
John Hart Power Project and Town Site, Campbell River, B.C.	1958	An aerial view of the John Hart power project and town site in Campbell River, B.C. A forest is shown surrounding the cleared area.
Wharf and Fishermen's Floats, Campbell River, B.C.	1953	An aerial view of the wharf and fishermen's floats at Campbell River, B.C.
Forbes Landing Near Campbell River BC	1930	A bear climbing a tree at Forbes Landing near Campbell River, B.C.
Bowie Arch, Stanley Park, Vancouver, B.C.	1920	Bowie Arch at Stanley Park in Vancouver, B.C. viewed from a distance. A walkway is shown leading up to the arch.
Lumberman's Arch, Stanley Park, Vancouver, B.C.	1918	Numerous people walking down the walkway leading up to the Lumberman's Arch at Stanley Park, B.C. The North Shore Mountains are shown in the distance.
Interior of Christ Church Cathedral Victoria, B.C.	1935	The interior of the Christ Church Cathedral in Victoria, B.C.
Elementary School, Dawson Creek, B.C.	1956	An elementary school in Dawson Creek, B.C.
Hasting-Str. Looking East, Vancouver, B.C.	1911	Hastings Street in Vancouver, B.C. looking east. Some storefronts, pedestrians and automobiles are shown.
Semi-Permanent Buildings, University of British Columbia, Vancouver, B.C.	1934	Semi-permanent buildings at the University of British Columbia in Vancouver, B.C. A parking lot with numerous automobiles in it is shown in the foreground to the right of the image.
Kelowna, B.C. Barnard Avenue; looking West from Palace Hotel	1906	Barnard Avenue in Kelowna, B.C. looking west from the Palace Hotel. Some storefronts are shown.
Bankhead Ranch Kelowna 1908	1908	Eleven men at a hunting party at Bankhead Ranch in Kelowna, B.C. One of the men is shown holding a young girl.
Kelowna Wins, Regatta Day at Kelowna, B.C.	1918	A scene from the Kelowna regatta. Numerous people are shown on boats.
Keremeos B.C.	1952	A street in Keremeos, B.C. Some storefronts and automobiles are shown.
Globe Hotel, Lytton, B.C.	1914	The Globe Hotel in Lytton, B.C. Several men are shown outside the hotel.
Manson's Landing-bortey? Id. B.C.	1961	An aerial view of a wharf at Manson's Landing, B.C. A few sea planes are shown parked by the wharf.
Maple Beach	1922	Several people shown at Maple Beach near Ladner, B.C.
Merritt, B.C.	1914	A street in Merritt, B.C. Some storefronts and pedestrians are shown.
Hotel, North Vancouver, B.C.	1909	A hotel in North Vancouver, B.C. Numerous people are shown on the lawn in front of the hotel. Banners are shown hanging on the front of the hotel.
Landing, North Vancouver, B.C.	1909	A ferry that just landed in North Vancouver, B.C. Numerous people are shown walking away from the ferry.
Agate Bay Fishing Camp Adams Lake, B.C.	1953	A driveway at the Agate Fishing Camp at Adams Lake, B.C. An automobile is shown parked beside the driveway.
Main Street, Ashcroft, B.C.	1912	Main Street in Ashcroft, B.C. Some storefronts and a person standing on the street are shown.
700 Miles Through B.C.	1911	A horse drawn wagon and three men at Ashcroft, B.C.
Cottages at Rocky Mountain Lodge, Lake Windermere, B.C.	1952	Two of the cottages at the Rocky Mountain Lodge at Windermere Lake, B.C. An automobile is shown parked beside one of the cottages.
Mc. Bride, B.C. July 1st. 1913	1914	Several horse drawn wagons in McBride, B.C. Mountains are shown in the background.
Mcleary's Lake, Returning to Camp with the Goods	1918	Three people getting out of their boat at Mcleary Lake, B.C.
Residence of C.W. Munro Esq. Camp River, Chilliwack B.C.	1910	The residence of C.W. Munro Esq. on the Camp River at Chilliwack, B.C. The residence is viewed from the opposite side of the river.
Ranch Farm RR2. Hope River Chilliwack-BC	1933	Three men with a horse drawn plow in Chilliwack, B.C.
Bill Bose Ox Team on way to Barkerville 1881	1929	A Bill Bose ox team in front of the Clinton Hotel on its way to Barkerville, B.C.
Scenes of Cranbrook, B.C.	1909	The government building in Cranbrook, B.C.
Creston & District	1943	A street in Creston, B.C. Some storefronts and automobiles are shown.
Copper Street, Greenwood, B.C.	1909	Copper Street in Greenwood, B.C. Some storefronts are shown.
Halcyon Hot Springs, B.C.	1908	The Halcyon Hot Springs Hotel at Halcyon Hot Springs, B.C.
Packing on the Chehalis Trail	1917	A man and several pack horses on the Chehalis Trail.
Seattle to Hazelton Overland Auto at End of Journey Hazelton Oct 5/11	1912	A crowd of people standing around an automobile at Hazelton, B.C.
Rupert Taylor Motel, Hope, B.C.	1952	The Rupert Taylor Motel in Hope, B.C. Some automobiles are shown parked in front of the motel.
Public School, Kamloops, B.C.	1944	A public school in Kamloops, B.C. Some students are shown outside of the school.
Esquimalt Naval Station, Victoria, B.C.	1909	Several ships in the harbour at the Esquimalt Naval Station.
Re-embarking for Esquimalt after the Ceremony 2-7-17	1917	Numerous sailors re-embarking for Esquimalt, B.C.
Grandview Camp, Qualicum Beach, Vancouver Island, B.C.	1941	Five different images of Grandview Camp at Qualicum Beach, B.C.
Tofino B.C.	1938	Several boats at the waterfront in Tofino, B.C.
Siwash Rock Stanley Park, Vancouver	1907	Siwash Rock at Stanley Park, B.C.
Cross Roads, Stanley Park, Vancouver B.C.	1909	The crossing point of two roads in Stanley Park, B.C.
Craigdarroch	1910	Craigdarroch Castle in Victoria, B.C.
H.M.S. Egeria in Dry Dock Esquimalt	1906	The H.M.S. Egeria in the dry dock at Esquimalt, B.C.
Government House, Victoria, B.C.	1915	Government House in Victoria, B.C.
Mushroom (Park) Victoria, B.C.	1915	A round, covered bench at Beacon Hill Park in Victoria, B.C.
Lily Pond, Beacon Hill Park, Victoria, B.C.	1909	The lily pond at Beacon Hill Park in Victoria, B.C. A fountain is shown in the pond.
Presbyterian Church, Cumberland, B.C.	1910	A Presbyterian church in Cumberland, B.C.
Andy Miller, Creston B.C.	1910	Two people standing in a farm field in Creston, B.C. A small dwelling is shown in the background.
Law Courts, Victoria, B.C.	1906	A court house in Victoria, B.C.
Church of Our Lady of the Holy Rosary, Vancouver, B.C.	1912	The interior of the Church of Our Lady of the Rosary in Vancouver, B.C.
Water Front, Vancouver, B.C.	1907	A waterfront area in Vancouver, B.C. Several vessels are shown along the waterfront.
Suspension Bridge, 1st Canyon ..., North Vancouver, ...	1910	A small boy standing on the suspension bridge at First Canyon in North Vancouver, B.C.
Waterfront and Shipping	1904	A waterfront shipping area in Vancouver, B.C. Numerous vessels are shown along the waterfront.
Seymour Narrows, Vancouver, B.C.	1905	A walkway along the waterfront at the Seymour Narrows at Vancouver, B.C. A small boat is shown at the shore.
Queen Victoria's Statue	1921	Statue of Queen Victoria in front of the Parliament Buildings in Victoria, B.C.
Hatley Park Victoria, B.C.	1924	Castle at Hatley Park in Victoria, B.C.
Bathing Beach, Gorge Park, Victoria, B.C.	1909	Bathing beach at Gorge Park in Victoria, B.C. Some people are shown on the beach, swimming and in boats on the water.
Watching the Boats From Gorge Bridge Victoria B.C.	1911	A crowd of people watching the boats from the Gorge Bridge in Victoria, B.C.
Jubilee Hospital, Victoria, B.C.	1907	Driveway leading up to Jubilee Hospital in Victoria, B.C.
Olympic Mountains from Victoria B.C.	1906	Olympic Mountains viewed from Victoria, B.C.
Group on the steps of Parliament Building with the L. Governor	1917	A large group of people on the steps of the British Columbia Parliament Buildings in Victoria, B.C. with the Lieutenant Governor in 1917.
Laying the Cornerstone of Tranquille Sanatorium, Nov. 11th '08	1908	Crowd of people observing the laying of the cornerstone of Tranquille Sanatorium.
A.H. Hoffer Station Master Kingsgate BC	1909	Photograph of A.H. Hoffer and a separate image of a cheque made out to A.H. Hoffer.
Assembly Hall, Government Buildings, Victoria, B.C.	1909	Interior of the assembly hall in the British Columbia Parliament Buildings in Victoria, B.C.
Buildings - Empress Hotel, Victoria	1919	Large group of people on the lawn in front of the British Columbia Parliament Buildings in Victoria, B.C. showing the Empress Hotel.
Dominion Trust Building, Vancouver, B.C.	1911	Dominion Trust Building in Vancouver, B.C. Some pedestrians are shown on the street beside the building.
Victory Square, Showing War Memorial, Vancouver, B.C.	1940	Victory Square in Vancouver, B.C. showing the War Memorial and Dominion Trust Building.
Yacht Racing, Cadboro Bay, Victoria B.C.	1921	A yacht race taking place at Cadboro Bay, B.C.
Forest Fire in the Selkirks	1914	Forest fire taking place in the Selkirk Mountains, B.C.
Lake of the Hanging Glaciers B.C.	1946	Man sitting on a rock fishing at Lake of the Hanging Glacier, B.C. The reflection of the surrounding mountain is shown on the lake.
Vaucroft, B.C.	1936	Row of five bungalows at Vaucroft, B.C. A wooden walkway is shown running along the front of the bungalows.
Metropolitan Methodist Church Victoria B.C.	1910	Metropolitan Methodist Church in Victoria, B.C.
Lewis Park, Courtenay, B.C.	1954	Two totem poles on either side of the driveway at Lewis Park in Courtenay, B.C. A woman is shown standing next to the fence beside one of the totem poles.
Hotel-Forbes Landing-Campbell River, B.C.	1930	Hotel at Forbes Landing in Campbell River, B.C. An automobile is shown parked next to the hotel to the left of the image.
Qualicum Beach, Vancouver Island, B.C.	1940	A street in Qualicum Beach, B.C. Some storefronts and automobiles are shown.
Nanaimo B.C.	1931	Malaspina Hotel in Nanaimo, B.C. Numerous automobiles are shown parked on the street in front of the hotel. Some pedestrians are also shown.
Millstone River Nanaimo; Millstone Falls	1906	One image of the Millstone River in Nanaimo, B.C. and a second image of Millstone Falls.
Coal-Loading Wharves, Nanaimo, B.C.	1911	Shipping wharves in Nanaimo, B.C. A ship is shown leaving the wharves.
War Memorial, Nanaimo, B.C.	1948	War memorial statue in Nanaimo, B.C.
Malaspina Gallery, Near Nanaimo, B.C.	1956	Two people in a small boat at the Malaspina Gallery near Nanaimo, B.C.
Mallispina Gallery, Nanaimo, B.C.	1906	Three men and a dog at the Malaspina Gallery near Nanaimo, B.C. A small boat is shown at the shore.
H.B.C. Fort Nanaimo B.C.	1952	Old Hudson's Bay Company fort in Nanaimo, B.C.
Front Street, Nanaimo, B.C.	1945	Front Street in Nanaimo, B.C. Some storefronts and automobiles are shown.
Prince Charles Hotel, Penticton, B.C.	1956	Prince Charles Hotel in Penticton, B.C. Some automobiles are shown.
Kelley's Kabins Penticton BC	1941	Kelley's Kabins in Penticton, B.C.
Penticton, B.C.	1936	Aerial view of a waterfront area of Penticton, B.C.
Johnston Street, Alberni, Vancouver Island, B.C.	1940	Johnston Street in Alberni, B.C. Some storefronts and automobiles are shown.
Acid Tower, Powell River, B.C.	1925	An acid tower in Powell River, B.C.
Trail B.C.	1917	Snow covered street in Trail, B.C. Some storefronts and an automobile are shown.
River St. Wardner, B.C.	1911	River Street in Wardner, B.C. Several dwellings are shown.
Getting on Fine in Victoria, B.C.	1906	Painting or drawing of two people sitting in front of a sunset.
Who am I for	1906	Painting or drawing of a heron standing in the water next to an infant on the shore.
Madam You Have Deceived Me	1906	Painting or drawing of a rooster, hen and three chicks.
Try this on a summer's night	1909	Painting of a man and woman sitting on hammock in front of the moon.
Have a Care	1907	Painting of some type of flower.
Coming Your Way	1905	Painting of a man walking down railroad tracks.
I'm looking O.K.	1907	Painting of a man.
You Why Don't You Write?	1908	Painting of a First Nations man sitting down holding a bottle in his hand.
When Shall We Three Meet Again?	1906	Painting of two horses with their heads over the side of a fence.
Ucluelet, B.C.	1962	A street in Ucluelet, B.C. Some automobiles and two storefronts are shown.
Vancouver's Newest and Most Progressive Departmental Store Pioneers-Established 1892	1911	Stark's Glasgow House department store in Vancouver, B.C.
Surf Bathing, English Bay, Vancouver, B.C.	1928	Large number of people at the English Bay beach in Vancouver, B.C. People are shown on the shore and in the water.
Main-Lobby - Hotel Dunsmuir, Vancouver, B.C.	1915	Main lobby at the Hotel Dunsmuir in Vancouver, B.C.
Dining Room, Glencoe Lodge, Vancouver, B.C.	1910	Dining room at the Glencoe Lodge in Vancouver, B.C.
Shawnigan Beach Hotel, Shawnigan Lake, B.C.	1962	Numerous people on the shore and in the water at the Shawnigan Beach Hotel at Shawnigan Lake, B.C.
Cougars, Sooke, B.C.	1933	Two men each with a dead cougar on their back. Each man also has a dog on a leash with them.
Sooke Harbour House, Whiffen Spit Beach, Sooke B.C.	1951	Sooke Harbour House at Whiffen Spit Beach in Sooke, B.C.
Quathiaski Cove, B.C.	1944	Small boat dock at Quathiaski Cove, B.C. Several boats are shown near the dock.
Mill Bay Tourist Resort	1958	Aerial view of the Mill Bay Tourist Resort on Vancouver Island, B.C.
Miracle Beach, V.I. B.C.	1954	A deer in front of a dwelling at Miracle Beach, B.C.
P.O. Ymir, B.C.	1914	Several people standing in front of the Ymir, B.C. post office.
Silhouett
Overlooking Burrard Inlet, Vancouver, B.C.	1910	View overlooking the harbour at Burrard Inlet in Vancouver, B.C. Several vessels are shown in the harbour.
Vancouver, B.C.	1938	View of Vancouver, B.C.
Empress Hotel & Post Office, Victoria, B.C.	1908	View of the Empress Hotel and post office in Victoria, B.C. The Inner Harbour is shown in the foreground.
Burrard Bridge, Vancouver BC	1932	View of the Burrard Bridge in Vancouver, B.C. Two small boats are shown in the foreground.
Approaching the Rockies, Leanchoil Mountain	1905	View of the Rocky Mountains from Leanchoil Mountain, B.C. Some railroad tracks are shown in the foreground.
Stanley Park and Gulf of Georgia From Grouse Mountain, Vancouver, B.C.	1937	View of Stanley Park and the Gulf of Georgia from Grouse Mountain, B.C. A skier is shown in the foreground to the left of the image.
Rossland B C	1909	View looking down a street in Rossland, B.C.
Croteau Camp, Forbidden Plateau, Near Courtenay, B.C.	1940	View looking out at the water from Croteau Camp at the Forbidden Plateau near Courtenay, B.C.
Picturesque scenery along the Nanimo River, Nanimo, B.C.	1918	View looking down the Nanaimo River at Nanaimo, B.C. The reflections of the surrounding trees are shown on the water.
Peachland, B.C. from the Lake	1914	View of Peachland, B.C. from the lake. A wharf is shown in the foreground.
Kanaka Creek Port Haney, B.C.	1908	View looking down Kanaka Creek at Port Haney, B.C.
Farm Scene, Vanderhoof, B.C.	1925	View of a farm field in Vanderhoof, B.C.
Little Qualicum River, V.I., B.C.	1932	View looking down the Little Qualicum River on Vancouver Island, B.C.
Tillicum Seaside Cottages Yellow Point V.I., B.C.	1950	View of the water from Tillicum Seaside Cottages at Yellow Point, B.C. A sailboat is shown at a small floating dock.
